# Social Login Registration Setting
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 372669146226-o07a7erkfg6bej4tkadnlkbbmqtrb4im.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: [ profile, email ]